### ISSUE TITLE
understand folding rules

### ISSUE THREAD

**Issue by Alexey-T** [ysdragon/ring-sublime#1]
I want to write parser for Ring.
Help pls to understand how functions/classes are folded. 

1. what is the function end? is it the 'return' token at the line start?

2. What is the 'class' end? some keyword at line start, or maybe just the file end? what if 2 classes exists in 1 file, how to find the end of 1st class?

3. what if 'func' or 'class' keyword appears not at the line start, can it be? then function end 'return' token must be shifted to the right (same count of spaces)?

**Comment by ysdragon** [comment]
Hi @Alexey-T,

> what is the function end? is it the 'return' token at the line start?

In Ring functions don't have a specific end keyword.
They typically end when:
1. A `return` statement is encountered at the beginning of a line.
2. The next function or class definition starts.
3. The end of the file is reached.

> What is the 'class' end? some keyword at line start, or maybe just the file end? what if 2 classes exists in 1 file, how to find the end of 1st class?

Classes in Ring also don't have a specific end keyword.
A class definition ends when:
1. Another class definition starts.
2. A function definition outside of any class starts.
3. The end of the file is reached.

> what if 'func' or 'class' keyword appears not at the line start, can it be? then function end 'return' token must be shifted to the right (same count of spaces)?

Yes, `func` or `class` can appear anywhere on a line in Ring. However, the `return` statement doesn't need to match the indentation of `func`. Indentation in Ring is not syntactically significant, so `return` can be at any indentation level and still end the function.


You can find more info here: [Language Specification](https://ring-lang.github.io/doc1.21.2/reference.html)
